create table if not exists public.leads_lab_runia (
  id bigint generated by default as identity primary key,
  negocio text,
  rubro text,
  web_actual text,
  branding text,
  objetivo text[] not null default '{}',
  tipo_web text,
  secciones text,
  nivel_diseno text,
  funcionalidades text[] not null default '{}',
  presupuesto text,
  tiempos text,
  pack_sugerido text not null,
  enviado_en timestamptz not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
